start mac/freebsd support

diff --git a/_bin/sys_config b/_bin/sys_config
--- a/_bin/sys_config
+++ b/_bin/sys_config
@@ -5,6 +5,15 @@
 # This program is free software: you can redistribute/modify under the terms of the GPL-v3 (https://www.gnu.org/licenses/gpl-3.0.html).
 # This program is distributed WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
+if [ "$OS" = Darwin ] ; then
+	realpath() {
+		case $1 in
+			/*) echo      $1 ;;
+			* ) echo $PWD/$1 ;;
+		esac
+	}
+fi
+
 MK_FILE=$( realpath ${1:-/dev/null})
 H_FILE=$(  realpath ${2:-/dev/null})
 SUM_FILE=$(realpath ${3:-/dev/null})
@@ -82,66 +91,90 @@ STD_INC_DIRS="$(echo $(realpath $(sed -e '1,/<.*>.*search starts/d' -e '/End of 
 # Python configuration (Python2 is optional)
 #
 
-config_python() {
-	python=$1
-	ver=$2
-	python=${python:-python$ver}
-	p=$(type -p $python || :)
-	[ "$p" ] || { msg="$python not found" ; return 1 ; }
-	python=$p
-	llp=$LD_LIBRARY_PATH                                                        # save LD_LIBARY_PATH
-	export LD_LIBRARY_PATH="$(dirname $(dirname $python))/lib:$LD_LIBRARY_PATH"
-	py_major=$($python -c 'import sys       ; print(sys.version_info.major                )')
-	py_minor=$($python -c 'import sys       ; print(sys.version_info.minor                )')
-	inc_dir=$( $python -c 'import sysconfig ; print(sysconfig.get_config_var("INCLUDEDIR"))')
-	inc_py=$(  $python -c 'import sysconfig ; print(sysconfig.get_config_var("INCLUDEPY" ))')
-	lib_base=$($python -c 'import sysconfig ; print(sysconfig.get_config_var("LDLIBRARY" ))')
-	lib_dir=$( $python -c 'import sysconfig ; print(sysconfig.get_config_var("LIBDIR"    ))')
-	case $ver in
-		2)
-			[ $py_major -eq 2 ] || { msg="$python version must be 2.x"          ; return 1 ; }
-			[ $py_minor -ge 7 ] || { msg="$python version must be at least 2.7" ; return 1 ; }
-		;;
-		3)
-			[ $py_major -eq 3 ] || { msg="$python version must be 3.x"          ; return 1 ; }
-			[ $py_minor -ge 6 ] || { msg="$python version must be at least 3.6" ; return 1 ; }
-		;;
-	esac
-	case "$lib_base" in
-		*.so | *.a ) ;;
-		*          ) msg="$python library $lib_base is not a python library" ; return 1 ;;
-	esac
-	case "$lib_dir/" in
-		/usr/lib/*  ) lib_dir= ;;
-		/usr/lib64/*) lib_dir= ;;
-	esac
-	[ ! "$lib_dir" ] || lib_opt=-L$lib_dir
-	cat <<-"EOF" >probe_python$ver.c
-		#include <Python.h>
-		int main() {
-			PyObject* none = Py_None ;
+case $OS in
+	#
+	Linux)
+		config_python() {
+			python=$1
+			ver=$2
+			python=${python:-python$ver}
+			p=$(type -p $python || :)
+			[ "$p" ] || { msg="$python not found" ; return 1 ; }
+			python=$p
+			llp=$LD_LIBRARY_PATH                                                        # save LD_LIBARY_PATH
+			export LD_LIBRARY_PATH="$(dirname $(dirname $python))/lib:$LD_LIBRARY_PATH"
+			py_major=$($python -c 'import sys       ; print(sys.version_info.major                )')
+			py_minor=$($python -c 'import sys       ; print(sys.version_info.minor                )')
+			inc_dir=$( $python -c 'import sysconfig ; print(sysconfig.get_config_var("INCLUDEDIR"))')
+			inc_py=$(  $python -c 'import sysconfig ; print(sysconfig.get_config_var("INCLUDEPY" ))')
+			lib_base=$($python -c 'import sysconfig ; print(sysconfig.get_config_var("LDLIBRARY" ))')
+			lib_dir=$( $python -c 'import sysconfig ; print(sysconfig.get_config_var("LIBDIR"    ))')
+			case $ver in
+				2)	[ $py_major -eq 2 ] || { msg="$python version must be 2.x"          ; return 1 ; }
+					[ $py_minor -ge 7 ] || { msg="$python version must be at least 2.7" ; return 1 ; }
+				;;
+				3)	[ $py_major -eq 3 ] || { msg="$python version must be 3.x"          ; return 1 ; }
+					[ $py_minor -ge 6 ] || { msg="$python version must be at least 3.6" ; return 1 ; }
+				;;
+			esac
+			case $lib_base in
+				*.so | *.a ) ;;
+				*          ) msg="$python library $lib_base is not a python library" ; return 1 ;;
+			esac
+			case $lib_dir/ in
+				/usr/lib/*  ) lib_dir= ;;
+				/usr/lib64/*) lib_dir= ;;
+			esac
+			[ ! "$lib_dir" ] || lib_opt=-L$lib_dir
+			cat <<-"EOF" >probe_python$ver.c
+				#include <Python.h>
+				int main() {
+					PyObject* none = Py_None ;
+				}
+			EOF
+			cc -o probe_python$ver -I$inc_py $lib_opt -xc probe_python$ver.c -l:$lib_base || { msg="$python is unusable as python library" ; return 1 ; }
+			eval "PYTHON${ver#3}=$python"
+			eval "PY${ver}_INCLUDEDIR=$inc_dir"
+			eval "PY${ver}_INCLUDEPY=$inc_py"
+			eval "PY${ver}_LIB_BASE=$lib_base"
+			eval "PY${ver}_LIB_DIR=$lib_dir"
+			case "$lib_base" in
+				*.so) eval "HAS_PY${ver}_DYN=1" ; echo "using $python as python$ver (version $py_major.$py_minor)"                                           >>$SUM_FILE ;;
+				*.a ) eval "HAS_PY${ver}_DYN=0" ; echo "using $python as python$ver (version $py_major.$py_minor) with static library (minimal job support)" >>$SUM_FILE ;;
+			esac
+			LD_LIBRARY_PATH=$llp                                                        # restore LD_LIBARY_PATH
 		}
-	EOF
-	cc -o probe_python$ver -I$inc_py $lib_opt -xc probe_python$ver.c -l:$lib_base || { msg="$python is unusable as python library" ; return 1 ; }
-	eval "PYTHON${ver#3}=$python"
-	eval "PY${ver}_INCLUDEDIR=$inc_dir"
-	eval "PY${ver}_INCLUDEPY=$inc_py"
-	eval "PY${ver}_LIB_BASE=$lib_base"
-	eval "PY${ver}_LIB_DIR=$lib_dir"
-	case "$lib_base" in
-		*.so) eval "HAS_PY${ver}_DYN=1" ; echo "using $python as python$ver (version $py_major.$py_minor)"                                           >>$SUM_FILE ;;
-		*.a ) eval "HAS_PY${ver}_DYN=0" ; echo "using $python as python$ver (version $py_major.$py_minor) with static library (minimal job support)" >>$SUM_FILE ;;
-	esac
-	LD_LIBRARY_PATH=$llp                                                        # restore LD_LIBARY_PATH
-}
-
-config_python "$PYTHON2" 2 || { echo "no python2 support ($msg)" >>$SUM_FILE ; PYTHON2= ; } # python2 is optional
-config_python "$PYTHON"  3 || { echo                      $msg   >>$ERR_FILE ; exit 1   ; } # python3 is compulsery
-
-if   [ "$PY2_LIB_DIR" -a "$PY3_LIB_DIR" ] ; then PY_LD_LIBRARY_PATH=$PY3_LIB_DIR:$PY2_LIB_DIR
-elif [ "$PY2_LIB_DIR"                   ] ; then PY_LD_LIBRARY_PATH=$PY2_LIB_DIR
-elif [ "$PY3_LIB_DIR"                   ] ; then PY_LD_LIBRARY_PATH=$PY3_LIB_DIR
-fi
+		#
+		config_python "$PYTHON2" 2 || { echo "no python2 support ($msg)" >>$SUM_FILE ; PYTHON2= ; } # python2 is optional
+		config_python "$PYTHON"  3 || { echo                      $msg   >>$ERR_FILE ; exit 1   ; } # python3 is compulsery
+		#
+		if   [ "$PY2_LIB_DIR" -a "$PY3_LIB_DIR" ] ; then PY_LD_LIBRARY_PATH=$PY3_LIB_DIR:$PY2_LIB_DIR
+		elif [ "$PY2_LIB_DIR"                   ] ; then PY_LD_LIBRARY_PATH=$PY2_LIB_DIR
+		elif [ "$PY3_LIB_DIR"                   ] ; then PY_LD_LIBRARY_PATH=$PY3_LIB_DIR
+		fi
+	;;
+	#
+	Darwin)
+		python=${PYTHON:-python3}
+		p=$(whence $python)
+		[ "$p" ] || { echo "${PYTHON:-python3} not found">>$ERR_FILE ; exit 1 ; }
+		python=$p
+		py_major=$($python -c 'import sys ; print(sys.version_info.major)')
+		py_minor=$($python -c 'import sys ; print(sys.version_info.minor)')
+		[ $py_major -eq 3 ] || { echo "$python version must be 3.x"          >>$ERR_FILE ; exit 1 ; }
+		[ $py_minor -ge 6 ] || { echo "$python version must be at least 3.6" >>$ERR_FILE ; exit 1 ; }
+		base=$($python -c 'import sysconfig ; print(sysconfig.get_config_var("base"))')
+		#
+		PYTHON=$python
+		PY3_INCLUDEDIR=
+		PY3_INCLUDEPY=$base/Headers
+		PY3_LIB_BASE=libpython3.$py_minor.dylib
+		PY3_LIB_DIR=$base/lib/python3.$py_minor/config-3.$py_minor-darwin
+		HAS_PY3_DYN=1
+		PY_LD_LIBRARY_PATH=$PY3_LIB_DIR
+	;;
+	#
+esac
 
 #
 # LD_SO_LIB & LD_SO_LIB32
@@ -178,7 +211,7 @@ case $CXX_FLAVOR in
 	gcc  ) ADDR2LINE=$CXX_DIR/addr2line      ;;
 	clang) ADDR2LINE=$CXX_DIR/llvm-addr2line ;;
 esac
-[ -x "$ADDR2LINE" ] || ADDR2LINE=$(type -p addr2line)
+[ -x "$ADDR2LINE" ] || ADDR2LINE=$(type -p addr2line ||:)
 
 #
 # HAS_CLOSE_RANGE
@@ -308,13 +341,11 @@ HAS_STACKTRACE=$((   ${LIB_STACKTRACE:+   1}))
 HAS_STACKTRACE_32=$((${LIB_STACKTRACE_32:+1}))
 #
 [ $HAS_STACKTRACE = 1 ] || echo "no stacktrace support, fall back to (lower quality back trace in case of crash) addr2line" >>$SUM_FILE
-SPLIT_DBG=$((   1-$HAS_STACKTRACE   ))
-SPLIT_DBG_32=$((1-$HAS_STACKTRACE_32))
 
 #
 # MAX_PID
 #
-MAX_PID=$(cat /proc/sys/kernel/pid_max)
+MAX_PID=$(cat /proc/sys/kernel/pid_max || echo 0)
 
 #
 # MUST_UNDEF_PTRACE_MACROS
@@ -354,7 +385,10 @@ cat <<"EOF" > stat.c
 	int main() { stat("",&buf) ; }
 EOF
 cc -o stat_trial -xc stat.c
-nm -D stat_trial > stat_trial.nm
+case $OS in
+	Linux ) nm -D stat_trial > stat_trial.nm ;;
+	Darwin) nm -g stat_trial > stat_trial.nm ;;
+esac
 NEED_STAT_WRAPPERS=$(( ! $(ok grep -wq stat stat_trial.nm) ))
 
 #
@@ -364,7 +398,7 @@ case $CXX_FLAVOR in
 	gcc  ) OBJCOPY=$CXX_DIR/objcopy      ;;
 	clang) OBJCOPY=$CXX_DIR/llvm-objcopy ;;
 esac
-[ -x "$OBJCOPY" ] || OBJCOPY=$(type -p objcopy)
+[ -x "$OBJCOPY" ] || OBJCOPY=$(type -p objcopy ||:)
 
 #
 # STD_LIBRARY_PATH & STD_LIBRARY_PATH_32
@@ -374,6 +408,14 @@ show_std_library_path() {
 }
 cc      -o std_library_path    -xc++ - <<< 'int main(){}' && STD_LIBRARY_PATH=$(   show_std_library_path ./std_library_path   )
 cc -m32 -o std_library_path_32 -xc++ - <<< 'int main(){}' && STD_LIBRARY_PATH_32=$(show_std_library_path ./std_library_path_32)
+
+#
+# SPLIT_DBG
+#
+if [ "$OBJCOPY" ] ; then
+	SPLIT_DBG=$((   1-$HAS_STACKTRACE   ))
+	SPLIT_DBG_32=$((1-$HAS_STACKTRACE_32))
+fi
 
 #
 # STD_PATH
